# .github/workflows/scheduled-builds.yml
name: Trigger GET dollar-notify CRON Schedule

on:
  schedule:
    # Runs "every day at 10am" (see https://crontab.guru)
    - cron: '0 10 * * *'
jobs:
  build:
    name: Trigger Site Rebuild
    runs-on: ubuntu-latest
    steps:
      - name: cURL request
        # Hit the webhook endpoint to rebuild  from the "main" branch
        run: curl https://dollar-notify-bot.vercel.app/dollar